### ISSUE TITLE
low priority: icon centering/spacing in footer is slightly different on resources and faq pages compared to other pages

### ISSUE THREAD

**Issue by musalbas** [celestiaorg/celestia.org_older#15]

**Comment by rootulp** [comment]
Is this resolved? Social icons in the footer appear spaced similarly on the home page, `/faq`, and `/resources`

![2022-04-01 19 06 43](https://user-images.githubusercontent.com/3699047/161352866-5b3e06eb-851c-4753-9920-be16e61ab91f.gif)
