### ISSUE TITLE
A ton of empty space when visiting https://celestia.org/#roadmap

### ISSUE THREAD

**Issue by alex-beckett** [celestiaorg/celestia.org_older#155]
When clicking on the 'see the roadmap' button on the hero section of the website the user gets taken to the roadmap section on the homepage, which contains a bunch of empty space between the blog section and footer boxes.

In addition, when the user gets taken to the roadmap section should they be able to scroll back up the homepage? Currently, they can't.

**Comment by musalbas** [comment]
Good find, when you click roadmap you can't scroll back up, this seems to be a bug.

I can't see what empty space you mean though, perhaps a screenshot would be helpful?

**Comment by alex-beckett** [comment]
Photo on top shows what the gap between the blog section and footer boxes should be. Photo on the bottom is what it looks like (the blank space goes a lot further down). 

<img width="1120" alt="ewfsdczx" src="https://user-images.githubusercontent.com/75361908/214129160-28bbefa7-fd1a-41e5-ad1a-7383724fd049.png">
<img width="1120" alt="vsddvz" src="https://user-images.githubusercontent.com/75361908/214129174-d2e7c45d-1669-45e8-a9e9-4801ad1192f9.png">

**Comment by musalbas** [comment]
Weird, what browser and OS are you using? I don't see the space on FireFox.

**Comment by alex-beckett** [comment]
Windows 11, tested on Brave and Chrome

**Comment by dmtrbrl** [comment]
Hey guys! The same issue is on Mac (all browsers).
I've submitted a PR with a fix.
