### ISSUE TITLE
"most navigations  buttons of this website aren’t working in both chrome and safari" on developer portal

### ISSUE THREAD

**Issue by musalbas** [celestiaorg/celestia.org_older#339]
reported by @omritoptix

![image](https://github.com/celestiaorg/celestia.org/assets/5038597/87c82fca-2522-475a-aa50-f111ea90b11a)
![image](https://github.com/celestiaorg/celestia.org/assets/5038597/c8fa5331-aa49-4831-a1fb-a5d230242f6b)
![image](https://github.com/celestiaorg/celestia.org/assets/5038597/944e2473-c840-4127-85e8-173e8dc35d52)

https://celestia.org/developer-portal/

**Comment by ogunleye0720** [comment]
hello @musalbas , I have just checked the reported issue with the link provided, and everything seems to be working perfectly.
