### ISSUE TITLE
Careers page not displaying correctly

### ISSUE THREAD

**Issue by bd21** [celestiaorg/celestia.org_older#75]
[https://celestia.org/careers/](url) shows html tags as plain text

`Cosmos SDK Engineer [Go]<div>Celestia Labs is seeking a remote full-time Cosmos-SDK Engineer to help build the Celestia state machine and tools for Cosmos-SDK based rollups.</div><div><br></div><div><b style="font-size: 18px">About Celestia</b></div><div>Celestia is the first modular blockchain network. By decoupling consensus from execution, Celestia enables anyone to easily deploy their own blockchain, without the overhead of bootstrapping a new consensus network. Blockchains on Celestia are free from constraints, making them scalable, sovereign, and secure.</div>`

**Comment by adlerjohn** [comment]
The offending line looks to be https://github.com/celestiaorg/celestia.org/blob/0e57c9c866e25f9f2eab79d23f1610a67f5874f5/src/pages/careers.js#L77, which includes the raw HTML of the description.

**Comment by alex-beckett** [comment]
Fixed in #77
