### ISSUE TITLE
Support node >=16

### ISSUE THREAD

**Issue by adlerjohn** [celestiaorg/celestia.org_older#80]
Node 14 is currently used in CI and to deploy the site: https://github.com/celestiaorg/celestia.org/blob/2f713b9354a38ce5f6851f701a84a086f7d4e548/.github/workflows/main.yml#L31

Moving to Node 16 or 18 doesn't work trivially because of https://github.com/nodejs/node-gyp/issues/1599#issuecomment-542141623. In order to make it easier for developers to build the website locally and since Node 14 will be EOL by April 2023 (https://nodejs.org/en/about/releases/), we should find a way to move this to Node 16 or even 18.

**Comment by musalbas** [comment]
fixed in https://github.com/celestiaorg/celestia.org/commit/250a35ac7d6bcd7878dc6e5bfb3d9d47d1897c2c
