### ISSUE TITLE
Some definitions are not the good ones on the website

### ISSUE THREAD

**Issue by Gunter038** [celestiaorg/celestia.org_older#81]
Hello, I just noticed that Validium's definition is not the good one, on the website : 

![image](https://user-images.githubusercontent.com/97455701/182568254-34a7c854-e5f8-48d9-bf5d-81d09d81ef48.png)

Whereas it is the good one on Github : 

![image](https://user-images.githubusercontent.com/97455701/182568758-cc0402d4-5db6-4f40-98fc-8fe5dabc33a1.png)

It is also the case with Volitions. I'll check all the definitions.

**Comment by alex-beckett** [comment]
Thanks for letting us know 👍
